### ISSUE TITLE
Why don't use this one? https://github.com/memwey/casbin-sqlx-adapter

### ISSUE THREAD

**Issue by hsluoyz** [Blank-Xu/sqlx-adapter#1]
Hi, there's already a sqlx adapter around: https://github.com/memwey/casbin-sqlx-adapter

Any reason to create a new one?

**Comment by Blank-Xu** [comment]
1. I'd like to keep this module clean, just an Adapter, the database connection should controlled by user himself.
2. I'd like to support different databases better.
3. High performance is another point.

**Comment by hsluoyz** [comment]
Great. Would you add README and badges for CI and coverage, so people can easily use it?

**Comment by Blank-Xu** [comment]
Sure.

I'll do it after all support databases tests finished.

**Comment by Blank-Xu** [comment]
I'd like to close this issue because most databases test has been finished.

And I'd like to create an oracle branch to support oracle database.

**Comment by hsluoyz** [comment]
@Blank-Xu can you add this adapter to the official list? https://casbin.org/docs/en/adapters

**Comment by Blank-Xu** [comment]
finished.
