### ISSUE TITLE
UpdateFilteredPolicies doesn't work with the latest Casbin version 2.65.0

### ISSUE THREAD

**Issue by bkuensting** [Blank-Xu/sqlx-adapter#3]
The returned `oldPolicies` from `UpdateFilteredPolicies` may contain empty strings for some V columns. It seems, the latest Casbin doesn't like that:

```go
func (model Model) RemovePoliciesWithAffected(sec string, ptype string, rules [][]string) [][]string {
	var affected [][]string
	for _, rule := range rules {
		index, ok := model[sec][ptype].PolicyMap[strings.Join(rule, DefaultSep)]
		if !ok {
			continue
		}
``` 

The `index, ok := model[sec][ptype].PolicyMap[strings.Join(rule, DefaultSep)]` is the problem.

The following workaround works for me:

``` go
func (p *Adapter) UpdateFilteredPolicies(sec, ptype string, newPolicies [][]string, fieldIndex int, fieldValues ...string) (oldPolicies [][]string, err error) {

// omitted some lines

        oldPolicies = make([][]string, 0, len(oldRows))
	for _, rule := range oldRows {
		var oldPolicy []string
		sliceRule := append([]string{}, rule.PType, rule.V0, rule.V1, rule.V2, rule.V3, rule.V4, rule.V5)
		for _, v := range sliceRule {
			if v == "" {
				continue
			}
			oldPolicy = append(oldPolicy, v)
		}
		oldPolicies = append(oldPolicies, oldPolicy)
	}

// omitted some lines

}
```

**Comment by hsluoyz** [comment]
@bkuensting hi, can you make a PR to fix it?

**Comment by bkuensting** [comment]
A PR is what I wanted to provide in the first place, but then I noticed that some tests failed. I tried to fix the tests, but due to my lack of internal knowledge of Casbin I had problems in doing so.

**Comment by bkuensting** [comment]
Not sure if I am correct, but it seems Casbin is now taking the model configuration correctly into account.

``` text
[request_definition]
r = sub, obj, act
```

With the above, Casbin stores three tokens in its internal model.

The following code line provides more than three tokens as a filter and I suspect that Casbin can't work with that.

``` go
testGetPolicy(t, e, [][]string{{"bob", "data1", "write", "test1", "test2", "test3"}})
```

The test output is:

``` text
adapter_test.go:369: Policy: 
         [] , supposed to be 
         [[bob data1 write test1 test2 test3]]
```

**Comment by bkuensting** [comment]
> @bkuensting can you find which release version/PR introduces this issue?

Can't really tell. I updated to the latest version of Casbin and ran into this issue while using `UpdateFilteredNamedPolicies`of the enforcer api. This was the first time I used `UpdateFilteredNamedPolicies`.

**Comment by Blank-Xu** [comment]
Seems like start from Casbin `V2.49.0`, the test functions could not pass. And some logics in Casbin has been changed.

**Comment by hsluoyz** [comment]
@Blank-Xu did this PR: https://github.com/casbin/casbin/pull/1020 introduce this bug? I didn't see any related code is changed.

**Comment by Blank-Xu** [comment]
@bkuensting Would you mind checkout `fix_issue#3` branch and test again?

**Comment by hsluoyz** [comment]
@bkuensting

**Comment by bkuensting** [comment]
Tested main with merged PR and works so far for me! Thank you :+1:
